In [1]:
import pandas as pd
import numpy as np

In [11]:
#Crea una Series con los valores [1, 2, 3, 4, 5] y aplica la función np.sqrt() sobre ella. Comprueba que el índice se preserva.

valores = np.array([1, 2, 3, 4, 5])
d1 = pd.Series(valores)
np.sqrt(d1)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
dtype: float64

In [12]:
np.random.seed(42)
pd.DataFrame(np.random.randint(1,11, size=(3, 3)))
np.log(d1).round(2)

0    0.00
1    0.69
2    1.10
3    1.39
4    1.61
dtype: float64

In [17]:
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2, 3], index=['b', 'c', 'd'])
s1 + s2

a     NaN
b    21.0
c    32.0
d     NaN
dtype: float64

In [18]:
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s3 = pd.Series([1, 2, np.nan], index=['b', 'c', 'd'])
s1.add(s3, fill_value=0)

a    10.0
b    21.0
c    32.0
d     NaN
dtype: float64

In [21]:
superficie = pd.Series({'España': 505900, 'Francia': 551700,
'Alemania': 357100, 'Italia': 301300})
poblacion = pd.Series({'España': 47_400_000, 'Francia': 68_000_000,
'Alemania': 84_400_000, 'Portugal': 10_300_000})
densidad = (poblacion / superficie).round(2)
print(densidad)

Alemania    236.35
España       93.69
Francia     123.26
Italia         NaN
Portugal       NaN
dtype: float64

In [34]:
df1 = pd.DataFrame({'X': [1, 2], 'Y': [3, 4]},
index=['fila1', 'fila2'])
df2 = pd.DataFrame({'Y': [10, 20, 30], 'Z': [40, 50, 60], 'X': [5, 6, 7]},
index=['fila1', 'fila2', 'fila3'])

df1 + df2

         X     Y   Z
fila1  6.0  13.0 NaN
fila2  8.0  24.0 NaN
fila3  NaN   NaN NaN

In [35]:
print(df1.add(df2, fill_value=0))

         X     Y     Z
fila1  6.0  13.0  40.0
fila2  8.0  24.0  50.0
fila3  7.0  30.0  60.0

In [36]:
media = df1.stack().mean()
df1.add(df2, fill_value=media)

         X     Y     Z
fila1  6.0  13.0  42.5
fila2  8.0  24.0  52.5
fila3  9.5  32.5  62.5

In [42]:
np.random.seed(0)
d1 = pd.DataFrame(np.random.randint(1, 100, (4, 4)))
res = d1 - d1.iloc[0]
print(res.iloc[0].eq(0).all())

True

In [54]:
ventas = pd.DataFrame(
{'Tienda_A': [100, 200, 150], 'Tienda_B': [80, 300, 120]},
index=['Producto1', 'Producto2', 'Producto3']
)
precio = pd.Series({'Producto1': 5.0, 'Producto2': 3.5, 'Producto3': 8.0})
ventas.mul(precio, axis=0)

           Tienda_A  Tienda_B
Producto1     500.0     400.0
Producto2     700.0    1050.0
Producto3    1200.0     960.0

In [56]:
tienda_c = pd.Series([50, 400], index=["Producto1", "Producto2"])
ventas["Tienda_C"] = tienda_c
ventas = ventas.fillna(0)
ventas.mul(precio, axis=0)

           Tienda_A  Tienda_B  Tienda_C
Producto1     500.0     400.0     250.0
Producto2     700.0    1050.0    1400.0
Producto3    1200.0     960.0       0.0