# <span style="color:Thistle">Indexación y Selección de Datos</span>

#### <span style="color:beige">Sesión 3</span>
---
Vamos a ver mecanismos equivalentes para acceder y modificar valores en objetos `Series` y `DataFrame` de Pandas. Son parecidos a los que vimos con NumPy.

Comenzaremos con el caso más sencillo: el objeto unidimensional `Series`, y luego pasaremos al más complejo `DataFrame` bidimensional.

---

## Selección de Datos en Series

Como vimos en la sesión anterior, un objeto `Series` se comporta en muchos aspectos como un array NumPy unidimensional y, en otros, como un diccionario estándar de Python. Tener en mente estas dos analogías nos ayuda a comprender los patrones de indexación y selección de datos.

### Series como diccionario

Al igual que un diccionario, el objeto `Series` establece una correspondencia entre un conjunto de claves y un conjunto de valores:

In [ ]:
import pandas as pd

# Crear una Serie con índice de letras
datos = pd.Series([0.25, 0.5, 0.75, 1.0],
                  index=['a', 'b', 'c', 'd'])
datos

np.float64(0.25)

In [2]:
# Acceso a un elemento por su índice (igual que en un diccionario)
datos['b']

np.float64(0.5)


También podemos usar expresiones y métodos típicos de diccionarios para examinar claves/índices y valores:

In [3]:
# Comprobar si una clave existe en la Serie
'a' in datos

True

In [4]:
# Obtener las claves (índices) de la Serie
datos.keys()

Index(['a', 'b', 'c', 'd'], dtype='str')

In [5]:
# Obtener pares (clave, valor) como lista de tuplas
list(datos.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]


Los objetos `Series` también pueden modificarse con sintaxis similar a la de los diccionarios. Del mismo modo que se puede extender un diccionario asignando a una nueva clave, se puede extender una `Series` asignando a un nuevo valor de índice:

In [6]:
# Agregar un nuevo elemento a la Serie
datos['e'] = 1.25
datos

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series como array unidimensional

Una `Series` amplía la interfaz tipo diccionario y proporciona selección de elementos al estilo array mediante los mismos mecanismos básicos que NumPy: *slicing*, *enmascaramiento* e *indexación múltiple*.

In [7]:
# Slicing por índice explícito (el índice final se INCLUYE)
datos['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [8]:
# Slicing por índice implícito entero (el índice final se EXCLUYE)
datos[0:2]

a    0.25
b    0.50
dtype: float64

In [9]:
# Máscaras booleanas: seleccionar valores dentro de un rango
datos[(datos > 0.3) & (datos < 0.8)]

b    0.50
c    0.75
dtype: float64

In [10]:
# Indexación múltiple: seleccionar múltiples elementos por nombre
datos[['a', 'e']]

a    0.25
e    1.25
dtype: float64



> ⚠️ **Nota importante sobre el slicing:** al usar índice explícito (`datos['a':'c']`), el índice final **se incluye**; al usar índice implícito entero (`datos[0:2]`), el índice final **se excluye**.

### Indexadores: loc e iloc

Estas convenciones pueden generar confusión. Por ejemplo, si una `Series` tiene un índice entero explícito, una operación de indexación como `datos[1]` usará el índice explícito, mientras que un slicing como `datos[1:3]` usará el índice implícito de Python.

In [11]:
# Serie con índice entero explícito (no empieza en 0)
datos = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
datos

1    a
3    b
5    c
dtype: str

In [12]:
# Al indexar con un entero, se usa el índice EXPLÍCITO (= definido por el programador)
datos[1]

'a'

**Salida esperada:** `'a'`

In [13]:
# Al hacer slicing, se usa el índice IMPLÍCITO (= definido por Python)
datos[1:3]

3    b
5    c
dtype: str

Para resolver esta ambigüedad, Pandas ofrece el método loc.

**`loc`** — siempre referencia el índice **explícito**:

In [14]:
# loc usa el índice explícito (=programador)
datos.loc[1]

'a'

In [15]:
# Slicing con loc: incluye el límite final
datos.loc[1:3]

1    a
3    b
dtype: str

**`iloc`** — siempre referencia el índice **implícito** (definido por Python):

In [16]:
# iloc usa la posición implícita (=python)
datos.iloc[1]

'b'

In [17]:
# Slicing con iloc: excluye el límite final (comportamiento estándar de Python)
datos.iloc[1:3]

3    b
5    c
dtype: str



> 💡 **Principio guía:** En Python, *"explícito es mejor que implícito"*. Usar `loc` e `iloc` hace el código más legible y evita bugs sutiles, especialmente con índices enteros. **Se recomienda usar siempre estos indexadores.**

## Selección de Datos en DataFrame

Recordemos que un `DataFrame` se comporta en muchos aspectos como un array bidimensional o estructurado, y en otros como un diccionario de objetos `Series` que comparten el mismo índice.

### DataFrame como diccionario

La primera analogía es pensar en el `DataFrame` como un diccionario de objetos `Series` relacionados. Retomemos el ejemplo de áreas y poblaciones de estados:

In [18]:
# Crear Series de área y población por estado
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Nueva York': 141297, 'Florida': 170312,
                  'Illinois': 149995})

pob = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'Nueva York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})

# Construir un DataFrame combinando ambas Series
datos = pd.DataFrame({'area': area, 'pob': pob})
datos

              area       pob
California  423967  38332521
Texas       695662  26448193
Nueva York  141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

Se puede acceder a cada `Series` (columna) mediante indexación de diccionario:

In [19]:
# Acceso a columna por nombre (estilo diccionario)
datos['area']

California    423967
Texas         695662
Nueva York    141297
Florida       170312
Illinois      149995
Name: area, dtype: int64



Equivalentemente, se puede acceder mediante atributo cuando el nombre de la columna es una cadena:

In [20]:
# Acceso a columna mediante atributo (notación con punto)
datos.area

California    423967
Texas         695662
Nueva York    141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Al igual que con `Series`, esta sintaxis tipo diccionario sirve también para añadir nuevas columnas:

In [21]:
# Añadir columna de densidad de población (hab/km²)
datos['densidad'] = datos['pob'] / datos['area']
datos

              area       pob    densidad
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
Nueva York  141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### DataFrame como array bidimensional

También podemos ver el `DataFrame` como un array bidimensional mejorado. Podemos inspeccionarlo con el atributo `values`:

In [22]:
# Ver los datos brutos como array NumPy
datos.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [23]:
# Transponer el DataFrame: intercambiar filas y columnas
datos.T

            California         Texas    Nueva York       Florida      Illinois
area      4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pob       3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
densidad  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

Con **`iloc`** podemos acceder a las filas y las columnas:

In [24]:
# iloc: primeras 3 filas, primeras 2 columnas (por posición)
datos.iloc[:3, :2]

              area       pob
California  423967  38332521
Texas       695662  26448193
Nueva York  141297  19651127

Con **`loc`** indexamos por etiquetas explícitas:

In [25]:
# loc: filas hasta 'Illinois' (inclusive), columnas hasta 'pob' (inclusive)
datos.loc[:'Illinois', :'pob']

              area       pob
California  423967  38332521
Texas       695662  26448193
Nueva York  141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

Dentro de estos indexadores podemos combinar máscaras booleanas e indexación múltiple:

In [26]:
# Seleccionar filas donde la densidad > 100, mostrando solo columnas 'pob' y 'densidad'
datos.loc[datos.densidad > 100, ['pob', 'densidad']]

                 pob    densidad
Nueva York  19651127  139.076746
Florida     19552860  114.806121



Estas convenciones de indexación también sirven para **modificar** valores:

In [27]:
# Modificar un valor concreto: fila 0, columna 2 (densidad de California)
datos.iloc[0, 2] = 90
datos

              area       pob    densidad
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
Nueva York  141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

También podemos usar máscaras booleanas como haciamos con NumPy:

In [28]:
# Enmascaramiento directo: también opera sobre FILAS
datos[datos.densidad > 100]

              area       pob    densidad
Nueva York  141297  19651127  139.076746
Florida     170312  19552860  114.806121


---

## Resumen

| Operación | Sintaxis | Resultado |
|---|---|---|
| Acceder a columna | `df['col']` o `df.col` | Serie |
| Acceder a fila por etiqueta | `df.loc['fila']` | Serie |
| Acceder a fila por posición | `df.iloc[n]` | Serie |
| Slicing de filas por etiqueta | `df.loc['a':'b']` | DataFrame |
| Slicing de filas por posición | `df.iloc[n:m]` | DataFrame |
| Slicing directo | `df[n:m]` | DataFrame (filas) |
| Enmascaramiento directo | `df[mask]` | DataFrame (filas) |
| Selección 2D con etiquetas | `df.loc[filas, cols]` | DataFrame |
| Selección 2D con posiciones | `df.iloc[filas, cols]` | DataFrame |