# <span style="color:Thistle">DataFrame de Pandas</span>

#### <span style="color:beige">Sesión 2</span>

---

La siguiente estructura fundamental en Pandas es el `DataFrame`. Al igual que la `Series`, el `DataFrame` puede entenderse como:

- Una **generalización de un array NumPy bidimensional** con índices de fila y nombres de columna flexibles.
- Una **especialización de un diccionario Python** que mapea nombres de columna a `Series` de datos.

---

### `DataFrame` como array NumPy generalizado

Si una `Series` es el análogo de un array unidimensional con índices flexibles, un `DataFrame` es el análogo de un array **bidimensional** con índices de fila y nombres de columna flexibles.

De la misma forma que se puede pensar en un array 2D como una secuencia ordenada de columnas de una dimensión, se puede pensar en un `DataFrame` como una secuencia de objetos `Series` **alineados** (es decir, que comparten el mismo índice).

Aquí tenemos un objeto `Series` con el área de cinco estados:

In [4]:
import numpy as np
import pandas as pd

area_dict = {
    'California': 423_967,
    'Texas':      695_662,
    'New York':   141_297,
    'Florida':    170_312,
    'Illinois':   149_995
}
area = pd.Series(area_dict)

area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

Y otro objeto `Series` con la población de los mismos 5 estados:

In [5]:
poblacion_dict = {
    'California': 38_332_521,
    'Texas':      26_448_193,
    'New York':   19_651_127,
    'Florida':    19_552_860,
    'Illinois':   12_882_135
}

# Lo convertimos a Series
poblacion = pd.Series(poblacion_dict)
poblacion

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Teniendo esta dos `Series`, podemos usar un diccionario para construir un único objeto bidimensional `DataFrame` que contenga ambas:

In [6]:
states = pd.DataFrame({'poblacion': poblacion,
                       'area': area})
states

            poblacion    area
California   38332521  423967
Texas        26448193  695662
New York     19651127  141297
Florida      19552860  170312
Illinois     12882135  149995

<div class="alert alert-block alert-success">
Fíjate que el DataFrame ha unido las dos Series, los índices siguen siendo las ciudades pero ha creado dos columnas cuyo nombre son poblacion y area.
</div>

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Qué ventaja nos ofrece unir estas Series en un DataFrame?
</div>

Al igual que la `Series`, el `DataFrame` tiene un atributo `.index` que da acceso a las etiquetas del índice:

In [7]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')

Además, el `DataFrame` tiene un atributo `.columns`, que también es un objeto `Index` con las etiquetas de las columnas:

In [8]:
states.columns

Index(['poblacion', 'area'], dtype='str')

---

### `DataFrame` como conjunto de Series

Un `DataFrame` mapea un nombre de columna a una `Series` de datos de esa columna.

Por ejemplo, pedir la columna `'area'` devuelve el objeto `Series` que contiene las áreas:

In [9]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

---

### Construcción de objetos `DataFrame`

Un `DataFrame` puede construirse de diversas maneras. Veamos varios ejemplos.

##### 1. A partir de un único objeto `Series`

Un `DataFrame` de una sola columna puede construirse a partir de una `Series`:

In [12]:
pd.DataFrame(poblacion, columns=['poblacion'])

            poblacion
California   38332521
Texas        26448193
New York     19651127
Florida      19552860
Illinois     12882135


##### 2. A partir de una lista de diccionarios

Cualquier lista de diccionarios puede convertirse en un `DataFrame`. Usamos una comprensión de lista para crear datos de ejemplo:

In [13]:
# Vamos a crear dos columnas:
# columna a, donde el valor de cada elemento COINCIDE con su índice
# columna b, donde el valor de cada elemento ES EL DOBLE de su índice 
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

<div class="alert alert-block alert-success">
Si no se definen índices, por defecto pondrá 0, 1, 2...
</div>


Incluso si algunas claves del diccionario faltan, Pandas las rellenará con valores `NaN` (*Not a Number*):

In [14]:
ejemplo2 = pd.DataFrame(
    [
        {'a': 1, 'b': 2}, 
        {'b': 3, 'c': 4}
    ]
)

<div class="alert alert-block alert-success">
En este ejemplo, hemos creado:

- Un elemento con columna a=1 y b=2.
- Otro emento con columna b=3 y c=4.
</div>

<div class="alert alert-block alert-info">
<b>Pregunta:</b> ¿Porqué en las columnas a y c tienen valores con .0 mientras que b no tiene ese .0?
</div>

In [ ]:
# Averigualo mirando de que tipo es cada columna.

##### 3. A partir de un diccionario de objetos `Series`

In [15]:
pd.DataFrame({'poblacion': poblacion,
              'area': area})

            poblacion    area
California   38332521  423967
Texas        26448193  695662
New York     19651127  141297
Florida      19552860  170312
Illinois     12882135  149995

#####  4. A partir de un array NumPy bidimensional

Dado un array 2D, podemos crear un `DataFrame` especificando los nombres de columnas e índices. Si se omiten, se usará un índice entero:

In [16]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.322555  0.359547
b  0.018899  0.736488
c  0.250887  0.788405

---

## Resumen

En estas sesiones iniciales hemos explorado dos de las estructuras fundamentales de Pandas:

| Estructura | Analogía | Característica clave |
|------------|----------|----------------------|
| `Series`   | Array NumPy 1D generalizado / Diccionario especializado | Índice explícito y tipado |
| `DataFrame`| Array NumPy 2D generalizado / Diccionario de `Series` | Índices de fila y columna flexibles |